package(default_visibility = ["//nth/strings/interpolate:__subpackages__"])

cc_library(
    name = "interpolate",
    hdrs = ["interpolate.h"],
    deps = [
        "//nth/meta:type",
    ],
)

cc_library(
    name = "parameter_range",
    hdrs = ["parameter_range.h"],
    visibility = ["//visibility:public"], # TODO
    deps = [],
)

# cc_test(
#     name = "parameter_tree_test",
#     srcs = ["parameter_tree_test.cc"],
#     deps = [
#         ":parameter_tree",
#         "//nth/test/raw:test",
#     ],
# )

cc_library(
    name = "validate",
    hdrs = ["validate.h"],
    deps = [],
)
