package(default_visibility = ["//visibility:private"])

cc_library(
    name = "interpolate",
    hdrs = ["interpolate.h"],
    visibility = ["//nth/strings/interpolate:__subpackages__"],
    deps = [
        "//nth/meta:type",
    ],
)


cc_library(
    name = "validate",
    hdrs = ["validate.h"],
    visibility = ["//nth/strings/interpolate:__subpackages__"],
    deps = [],
)
