site_name: nth - A collection of C++ Libraries
nav:
  - Home: index.md
  - Libraries:
    #- algorithm: algorithm.md
    - base:
      - attributes: base/attributes.md
      - core: base/core.md
      - indestructible: base/indestructible.md
      - macros: base/macros.md
      - pack: base/pack.md
      - platform: base/platform.md
      - section: base/section.md
    #- commandline: commandline.md
    - container:
      - stack: container/stack.md
    - debug:
      #- contracts: debug/contracts.md
      - log: debug/log.md
      #- property: debug/property.md
      - unimplemented: debug/unimplemented.md
      - unreachable: debug/unreachable.md
      #- source_location: debug/source_location.md
      #- trace: debug/trace.md
    # - dynamic: dynamic.md
    - format:
      - format: format/format.md
      - cc: format/cc.md
      - json: format/json.md
      - interpolate: format/interpolate.md
    #- hash: hash.md
    - io:
      - reader:
        - reader: io/reader/reader.md
        - file: io/reader/file.md
        - string: io/reader/string.md
      - writer:
        - writer: io/writer/writer.md
        - file: io/writer/file.md
        - "null": io/writer/null.md
        - string: io/writer/string.md
    #- memory: memory.md
    #- meta: meta.md
    #- numeric: numeric.md
    - process:
      - env: process/env.md
    #- registration: registration.md
    #- strings: strings.md
    #- test: test.md
    - try: try.md
    - types:
      - structure: types/structure.md
    #- utility: utility.md
theme:
  name: readthedocs
