load("//nth/configuration:build_settings.bzl", "nth_configuration_target")

package(default_visibility = ["//visibility:public"])

label_flag(
    name = "configuration",
    build_setting_default = "//nth/configuration/default",
)
 
nth_configuration_target(
    name = "verbosity",
)
