package(default_visibility = ["//visibility:public"])

cc_library(
    name = "interval",
    hdrs = ["interval.h"],
    deps = [],
)

cc_test(
    name = "interval_test",
    srcs = ["interval_test.cc"],
    deps = [
        ":interval",
        "@com_google_googletest//:gtest_main",
    ],
)
