package(default_visibility = ["//visibility:private"])

cc_library(
    name = "integer",
    visibility = ["//visibility:public"],
    hdrs = ["integer.h"],
    srcs = ["integer.cc"],
    deps = []
)

# cc_test(
#     name = "integer_test",
#     srcs = ["integer_test.cc"],
#     deps = [
#         ":integer",
#         "@com_google_absl//absl/hash:hash_testing",
#         "@com_google_googletest//:gtest_main",
#     ]
# )
