load("//nth/configuration:build_settings.bzl", "nth_configuration")

cc_library(
    name = "verbosity",
    copts = ["-ferror-limit=1"],
    hdrs = ["verbosity.h"],
)

nth_configuration(
    name = "unconfigured"
)
