package(default_visibility = ["//visibility:public"])

cc_library(
    name = "format",
    hdrs = ["format.h"],
    deps = [
      "//nth/format/internal:format",
      "//nth/io/writer",
      "//nth/memory:bytes",
      "//nth/meta:type",
    ],
)
