package(default_visibility = ["//visibility:public"])

cc_library(
    name = "format",
    hdrs = ["format.h"],
    srcs = [
        "common_formatters.h",
        "common_defaults.h",
    ],
    deps = [
      "//nth/io/writer",
      "//nth/memory:bytes",
      "//nth/meta:type",
    ],
)
