package(default_visibility = ["//visibility:public"])

cc_library(
    name = "fstat",
    hdrs = ["fstat.h"],
    srcs = ["fstat.cc"],
    deps = [
        "//nth/base:attributes",
        "//nth/test:fakeable_function",
    ],
)

cc_library(
    name = "lseek",
    hdrs = ["lseek.h"],
    srcs = ["lseek.cc"],
    deps = [
        "//nth/base:attributes",
        "//nth/test:fakeable_function",
    ],
)

cc_library(
    name = "open",
    hdrs = ["open.h"],
    srcs = ["open.cc"],
    deps = [
        "//nth/base:attributes",
        "//nth/test:fakeable_function",
    ],
)

cc_library(
    name = "read",
    hdrs = ["read.h"],
    srcs = ["read.cc"],
    deps = [
        "//nth/base:attributes",
        "//nth/test:fakeable_function",
    ],
)
