package(default_visibility = ["//visibility:public"])

cc_library(
    name = "attributes",
    hdrs = ["attributes.h"],
    deps = [],
)

cc_test(
    name = "attributes_test",
    srcs = ["attributes_test.cc"],
    deps = [":attributes"],
)

cc_library(
    name = "configuration",
    hdrs = ["configuration.h"],
    deps = [],
)

cc_library(
    name = "macros",
    hdrs = ["macros.h"],
    deps = [],
)

cc_test(
    name = "macros_test",
    srcs = ["macros_test.cc"],
    deps = [
        ":macros"
    ],
)
