package(default_visibility = ["//nth/format:__subpackages__"])

cc_library(
    name = "format",
    hdrs = ["format.h"],
    deps = [
        "//nth/memory:bytes",
        "//nth/meta:type",
    ],
)
