load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "try",
    hdrs = [
        "internal/handler.h",
        "internal/try.h",
        "try.h",
    ],
    deps = [
        "//nth/base:attributes",
        "//nth/base:core",
        "//nth/base:macros",
        "//nth/debug/log",
        "//nth/meta:type",
        "//nth/meta/concepts:core",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
    ],
    defines = select({
        ":dfatal_on": ["NTH_DFATAL"],
        "//conditions:default": [],
    }),
)

config_setting(
    name = "dfatal_on",
    flag_values = {":dfatal": "true"},
    visibility = ["//visibility:private"],
)

bool_flag(
    name = "dfatal",
    build_setting_default = True,
)

cc_test(
    name = "try_test",
    srcs = ["try_test.cc"],
    deps = [
        ":try",
        "//nth/test:main",
    ],
)

cc_test(
    name = "try_dfatal_test",
    srcs = ["try_test.cc"],
    local_defines = ["NTH_DFATAL"],
    deps = [
        ":try",
        "//nth/test:main",
    ],
)
