name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64
      - name: Test Debug Build
        run: >-
          bazel test -c dbg --copt=-DJASMIN_DEBUG ...
      - name: Test Hardened Build
        run: >-
          bazel test -c opt --copt=-DJASMIN_DEBUG ...
      - name: Test Optimized Build
        run: >-
          bazel test -c opt ...
